
title: Benoit Seguin, Consulting & Software Development
email: contact@benoitseguin.net
description: > # this means to ignore newlines until "baseurl:"
  Public website of Benoit Seguin, Independent Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Seguin_Be
github_username:  SeguinBe
google_analytics: UA-87689861-1

collections:
  projects:
    order:
      - e-rara_tr.md
      - impresso2.md
      - artlab.md
      - impresso1.md
      - thesis.md
    output: True

# Build settings
theme: minima
