
title: Benoit Seguin, PhD
email: contact@benoitseguin.net
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Benoit Seguin, Independent Consultant
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Seguin_Be
github_username:  SeguinBe
google_analytics: UA-87689861-1

# Build settings
theme: minima
